image: Visual Studio 2019
build_script:
  - dotnet restore ./With.sln
  - dotnet build ./src/With
test_script:
  - dotnet test ./tests/Tests
  - dotnet test ./tests/TestsFs
branches:
  only: 
    - master
    - v6
