image: Visual Studio 2019
install:
  - cmd: choco install dotnetcore-sdk -y
build_script:
  - dotnet restore ./With.sln
  - dotnet build ./With.sln
test_script:
  - dotnet test ./tests/Tests
  - dotnet test ./tests/TestsFs
branches:
  only: 
    - master
    - v6
